spring.application.name=jwtDemo

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://ep-spring-heart-aqye8zgw.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_knmMxV68ORPW

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=KCNMSalWLClQkjUJYvtBJscaLkTIF88VhWBhWd6OtEm
app.jwt.expiration-ms=3600000

# Razorpay
razorpay.key-id=rzp_test_ShH5hjcEgz4HqN
razorpay.key-secret=21AndasiMBcbWaB9LcHr94Ud
razorpay.currency=INR